#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# Default values for free5gc-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  name: free5gc
  userPlaneArchitecture: ulcl  # possible values are "single" and "ulcl"
  nrf:
    service:
      name: nrf-nnrf
      type: ClusterIP
      port: "8000"
      nodePort: "30800"
  sbi:
    scheme: http
  amf:
    n2if:  # NGAP
      ipAddress: 10.100.50.249
    service:
      ngap:
        enabled: true
        name: amf-n2
        port: 38412
        nodeport: 31412
        protocol: SCTP
        type: NodePort
  smf1:
    n4if:
      ipAddress: 10.100.50.244
  smf2:
    n4if:
      ipAddress: 10.100.50.245
  #Global network parametes
  n2network:
    enabled: true
    name: n2network
    type: ipvlan
    masterIf: eth0
    subnetIP: 10.100.50.248
    cidr: 29
    gatewayIP: 10.100.50.254
    excludeIP: 10.100.50.254
  n3network:
    enabled: true
    name: n3network
    type: ipvlan
    masterIf: eth0
    subnetIP: 10.100.50.232
    cidr: 29
    gatewayIP: 10.100.50.238
    excludeIP: 10.100.50.238
  n4network:
    enabled: true
    name: n4network
    type: ipvlan
    masterIf: eth0
    subnetIP: 10.100.50.240
    cidr: 29
    gatewayIP: 10.100.50.246
    excludeIP: 10.100.50.246
  n6network:
    enabled: true
    name: n6network
    type: ipvlan
    masterIf: eth1
    subnetIP: 10.0.2.0
    cidr: 24
    gatewayIP: 10.0.2.1
    excludeIP: 10.0.2.254
  n9network:
    enabled: true
    name: n9network
    type: ipvlan
    masterIf: eth0
    subnetIP: 10.100.50.224
    cidr: 29
    gatewayIP: 10.100.50.230
    excludeIP: 10.100.50.230

free5gc-upf:
  upf1:
    podSecurityContext:
      sysctls:
        - name: net.ipv4.ip_forward
          value: "1"
    n6if:
      ipAddress: 10.0.2.100
  upf2:
    podSecurityContext:
      sysctls:
        - name: net.ipv4.ip_forward
          value: "1"
    n6if:
      ipAddress: 10.0.2.101
  upfb:
    podSecurityContext:
      sysctls:
        - name: net.ipv4.ip_forward
          value: "1"
    n6if:
      ipAddress: 10.0.2.102
  upfb2:
    podSecurityContext:
      sysctls:
        - name: net.ipv4.ip_forward
          value: "1"
    n6if:
      ipAddress: 10.0.2.103

# These parameters can be used to enable/disable deployment of subcharts
deployMongoDb: true
deployAmf: true
deployAusf: true
deployChf: true
deployN3iwf: false
deployNef: true
deployNrf: true
deployNssf: true
deployPcf: true
deploySmf: true
deployUdm: true
deployUdr: true
deployUpf: true
deployWebui: true
deployDbPython: true

# Disable the deployment of mongodb as an NRF subchart
free5gc-nrf:
  db:
    enabled: false

# This section can be used to override the default values in the MongoDB chart
mongodb:
  fullnameOverride: "mongodb"
  useStatefulSet: true
  auth:
    enabled: false
  persistence:
    size: 6Gi
    mountPath: /bitnami/mongodb/data/db/
  service:
    name: mongodb
    type: ClusterIP
    port: 27017
    nodePort: "30017"
